### PR TITLE
Observed values in iOS 14

### PR DESCRIPTION
**Pull request by Schramp**
Don't know how you want to handle these kind  of observations. What version are you working on?

### CODE REVIEW

**Comment by joachimmetz** [comment]
Thanks for adding the observations, I'll have a look when time permits

> Don't know how you want to handle these kind of observations.

The proposed method is fine, ideally test data is reproducible e.g. https://github.com/dfirlabs/unified-logging-specimens

> What version are you working on?

Mac OS mostly https://github.com/libyal/dtformats/blob/main/documentation/Apple%20Unified%20Logging%20and%20Activity%20Tracing%20formats.asciidoc#15-test-versions

**Comment by Schramp** [comment]
I am working on

Software Version 16.1 [20B82]
Model iPhone 14 Plus [iPhone14,8 D28AP]

Method for testing:
1. Use iPhone to generate data
2. Mac Ventura 13.2.1 "Log collect --device--udid [device-id]"
3. Mac Ventura 13.2.1 "Log show  [path] > ground-thruth-events"
4. UnifiedLogReader.py -> to-validate-events
5. re-order to-validate-events and diff to ground-thruth-events

Current challenges in diffing:
1. timestamp difference is the last digit (micro-seconds)
2. Small changes in ordering

Ultimate Goal: get null output from "diff -w", but satisfied when differences seem irrelevant at first glance.

Current work: trying to remove all errors and looking at your documentation and updating the code at https://github.com/Schramp/UnifiedLogReader

**Comment by joachimmetz** [comment]
> Small changes in ordering

Note that `log` does not necessarily prints in chronological order something I put together to compare JSON output https://github.com/libyal/yaltests/blob/main/dtformats/compare_json.py

**Comment by joachimmetz** [comment]
> Current challenges in diffing:

some additional challenges

* parent activity ID is sometimes derived and sometimes not, but full method is not known yet
* when a message is truncated, when and where `<...>` is used

**Review by joachimmetz — COMMENTED** [review]
LGTM

**Pull request merged**
