### PR TITLE
[WIP] Add macOS spotlight v2 parser & documentation

### PR DESCRIPTION
**Pull request by everestmz**

### CODE REVIEW

**Comment by ydkhatri** [comment]
FYI, my paper on spotlight was officially published yesterday (11 months after submission!). It has the format documented, but there were some discoveries since then, so the code on my [github repo](https://github.com/ydkhatri/spotlight_parser) is the best source for updated info.
https://www.sciencedirect.com/science/article/pii/S1742287618300860?dgcid=author

**Comment by joachimmetz** [comment]
@ydkhatri thanks for the heads up

**Comment by joachimmetz** [comment]
@everestmz thx for the WIP PR, I'll salvage the reusable parts and integrate them.

**Comment by joachimmetz** [comment]
@everestmz thx for you work on this. I've used what I've can and implemented a first iteration in https://github.com/libyal/dtformats/commit/05ec3e4dd87bc9a779b4e2b354ced69883240017

Closing this PR

**Pull request closed without merging**
